---
title: "Day 3 R"
author: "Harish Chockalingam"
date: "9/19/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Dplyr

```{r}
generation<-read.csv(here::here("data/generation.csv"),stringsAsFactors=F)

imports<-read.csv(here::here("data/imports.csv"),stringsAsFactors=F)

library(lubridate)
generation$datetime<-as_datetime(generation$datetime)
class(generation$datetime)

imports$datetime<-as_datetime(imports$datetime)
class(imports$datetime)

library(reshape2)
long_gen<-melt(generation,id.vars="datetime",variable.name="source", value.name="usage")
head(long_gen)
long_gen[order(long_gen$datetime)[1:20],]

merged_energy<-merge(generation,imports,by="datetime")

long_merged_energy<-melt(merged_energy,id.vars="datetime",variable.name="source",value.name="usage")
head(long_merged_energy)

library(dplyr)
tmp<-select(merged_energy,biogas,biomass,geothermal,solar)
names(tmp)

tmp<-select(merged_energy,contains("hydro"),starts_with("bio"))
names(tmp)

tmp<-filter(merged_energy,imports>7000, natural_gas<7000)
nrow(tmp)

tmp<-mutate(long_merged_energy,log_usage=log(usage))
head(tmp)

summarize(long_merged_energy,total=sum(usage,na.rm=T))
summarize(long_merged_energy,mean_cons=mean(usage,na.rm=T))

long_merged_energy %>%
  filter(source=="geothermal")%>%
  select(-datetime)%>% #drops datetime
  mutate(log_usage =log(usage))%>%
  summarize(mean_log_usage=mean(log_usage,na.rm=T))

merged_energy %>%
  select(-datetime) %>%
  mutate(total_usage=rowSums(.,na.rm=T))%>% #the dot indicates the row of the datetime that's dropped through the pipping in the previous line
  
  summarize(mean_log_usage=mean(total_usage,na.rm=T))

merged_energy %>%
  select(contains("hydro")) %>%
  mutate(total_hydro=rowSums(.,na.rm=T)) %>%
  summarize(mean_hydro=mean(total_hydro, na.rm=T))

merged_energy %>%
  select(datetime,contains("hydro"),contains("bio"))%>%
  melt(id.vars="datetime",variable.name="source",value.name="usage")%>%
  group_by(source)%>%
  summarize(mean_usage=mean(usage,na.rm=T))
  
  
```
